name: CI Maven

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Doodle Modules
        run: |
          cat << EOF > DOODLE
          doodle-build doodle-socket doodle-design doodle-boot \
          doodle-broker
          EOF
          curl https://raw.githubusercontent.com/org-doodle/doodle-design/main/Makefile -o Makefile
          make DOODLE_GIT=https://github.com/org-doodle install

      - name: Checkout coding style
        run: ./mvnw spotless:check

      - name: Build with Maven
        run: ./mvnw package -B
